name: main_workflow
on:
  push:
    branches: [nodejs_jest_job]

jobs:
  linter-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          LINTER_RULES_PATH: /    
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  jest_job:
    runs-on: ubuntu-latest
    needs: linter-job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Jest Test
        run: npm install && npm run test
