name: main_workflow

on:
  push:
    branches: [readme-job]
 
jobs:
  jest_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Jest Test
        run: npm install && npm run test
  modify-readme:
    runs-on: ubuntu-latest
    needs: jest_job
    if: ${{ always() }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: deps
        run: sudo apt-get install -y graphicsmagick

      - uses: ./.github/actions/change-readme/
        with:
          frase_positiva: 'Los tests han funcionado'
          frase_negativa: 'Los tests han fallado'
          resultado_tests: ${{ needs.jest-job.result }}

      - name: Push
        run: |
          git config user.email "rafaelferreralcaraz@gmail.com"
          git config user.name "Rafa Ferrer"
          git add .
          git commit -m "Readme practica"
          git --no-pager log
          echo token: ${{ secrets.GIT_TOKEN }}
          git remote set-url origin https://RFerrerIesEstacio:${{ secrets.GIT_TOKEN }}@github.com/RFerrerIesEstacio/actividadGitHubActions.git
          git push origin readme-job
      

