name: main_workflow
on: push

jobs:
  linter-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          LINTER_RULES_PATH: /    
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  jest-job:
    runs-on: ubuntu-latest
    needs: linter-job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Jest Test
        run: npm install && npm run test
  enviroment_test_execution:
    runs-on: ubuntu-latest
    needs: [linter-job, jest-job]
    env:
      DESTINATION_PERSON: '2DAW'
    steps:
      - name: msg
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: ${{env.DESTINATION_PERSON}}

