name: main_workflow
on: push

jobs:
  linter-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          LINTER_RULES_PATH: /    
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

